workflows:
  jacktrack-android-build:
    name: JackTrack Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.jacktrack"  # Replace with your actual package name
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - 666gardo@gmail.com  # (Optional) replace with your email to receive build notifications

  jacktrack-web-build:
    name: JackTrack Web Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build Web
        script: |
          flutter build web
    artifacts:
      - build/web/**


